# Generated by Django 5.1.7 on 2025-03-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=20)),
                ('descricaoEvento', models.CharField(max_length=100)),
                ('dataHora', models.DateTimeField()),
                ('localEvento', models.CharField(blank=True, max_length=20)),
                ('categoriaEvento', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
