# Generated by Django 5.1.7 on 2025-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricaoEvento',
            field=models.TextField(max_length=100),
        ),
    ]
